from typing import Any, List, Mapping, Optional

import requests

from langchain.callbacks.manager import CallbackManagerForLLMRun
from langchain.llms.base import LLM
from langchain.llms.utils import enforce_stop_tokens
from langchain.pydantic_v1 import Extra

class KserveML(LLM):
    """KserveML LLM service.

    Example:
        .. code-block:: python

            from langchain.llms import KserveML
            endpoint_url = (
                "https://models.hosted-on.kserve.hosting/v2/models/my-model/infer"
            )
            kserve_llm = KserveML(endpoint_url=endpoint_url)
    """

    endpoint_url: str = (
        "https://models.hosted-on.kserve.hosting/v2/models/my-model/infer"
    )
    """Endpoint URL to use."""
    inject_instruction_format: bool = False
    """Whether to inject the instruction format into the prompt."""
    model_kwargs: Optional[dict] = None
    """Keyword arguments to pass to the model."""
    retry_sleep: float = 1.0
    """How long to try sleeping for if a rate limit is encountered"""

    class Config:
        """Configuration for this pydantic object."""

        extra = Extra.forbid

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        """Get the identifying parameters."""
        _model_kwargs = self.model_kwargs or {}
        return {
            **{"endpoint_url": self.endpoint_url},
            **{"model_kwargs": _model_kwargs},
        }

    @property
    def _llm_type(self) -> str:
        """Return type of llm."""
        return "kserve"

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        is_retry: bool = False,
        **kwargs: Any,
    ) -> str:
        """Call out to a KserveML LLM inference endpoint.

        Args:
            prompt: The prompt to pass into the model.
            stop: Optional list of stop words to use when generating.

        Returns:
            The string generated by the model.

        Example:
            .. code-block:: python

                response = kserve_llm("Tell me a joke.")
        """
        _model_kwargs = self.model_kwargs or {}

        payload = {
            "id": "1",
            "inputs": [
                {
                "name": "input0",
                "shape": [-1],
                "datatype": "BYTES",
                "data": [prompt]
                }
            ]
        }
        payload.update(_model_kwargs)
        payload.update(kwargs)
        #print(f"Sending request to {self.endpoint_url} with payload: {payload}")  # Debug output

        # send request
        try:
            response = requests.post(self.endpoint_url, json=payload)
            #print(f"Response received: {response.text}")  # Debug output
        except requests.exceptions.RequestException as e:
            raise ValueError(f"Error raised by inference endpoint: {e}")

        try:
            #print (response.status_code)
            if response.status_code == 500:
                if not is_retry:
                    import time

                    time.sleep(self.retry_sleep)

                    return self._call(prompt, stop, run_manager, is_retry=True)

                raise ValueError(
                    f"Error raised by inference API: 500, server maybe not ready yet"
                    f"{response.text}"
                )
            parsed_response = response.json()
            text = parsed_response["outputs"][0]["data"][0]

            #If prompt is part of the Answer, remove that part
            if text.startswith(prompt):
                text = text[len(prompt):]

            #remove Answer part
            keyword = "Answer: "
            if keyword in text:
                text= text[text.index(keyword) + len(keyword):]

            return text

        except requests.exceptions.JSONDecodeError as e:
            raise ValueError(
                f"Error raised by inference API: {e}.\nResponse: {response.text}"
            )
